### ISSUE TITLE
👀

### ISSUE THREAD

**Issue by sampoder** [cjdenio/scrapbook-streaks-extension#1]

**Comment by cjdenio** [comment]
:eyes: 

This basically lets you see people's full streak counts on their scrapbook pages and on [streaks.hackclub.com](https://streaks.hackclub.com).

![image](https://user-images.githubusercontent.com/34525547/86604327-3b953580-bf73-11ea-87fb-d5440338f69f.png)

**Comment by sampoder** [comment]
hackkkeeerrrrr

**Comment by sampoder** [comment]
but cool
